version: 0.2

phases:
  install:
    commands:
      - echo Install phase started... 
      - npm install -g hexo-cli
      - npm install
      - apt-get update
      - apt-get install -y awscli

  build: 
    commands:
      - echo Build phase started...
      - hexo clean
      - hexo generate
      
  post_build: 
    commands:
      - echo Post-Build phase started...
      - cd public/ && aws s3 sync . s3://cessna.cloud/